language: node_js
node_js:
  - '8'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
  - npm run install:demo
  - npm run build
before_script: greenkeeper-lockfile-update
script:
  - npm run lint
after_script: greenkeeper-lockfile-upload
notifications:
  email: false
  slack:
    rooms:
      secure: fnYQKOfL+nN2Qi6WRwrtCebFvLMHLMqJos74qDLm6C8ZJobc5dz2e6ZMiny2MwrTB4m/pzGaoTTcYiDDEAPzBb17FuSVAWzUaOPr0u6GXbM08+w8L7So04xXvszpdBsYHkRAeDmgMDMadLFm0JpH3MBJPG7cQYzUK+VO4hoXSV4IMab2+1zPOqggbvPq4D64/268jreeq2gnq6QyKQ6ti1XdfFogsl+OO+1yFhhsmiAKEQt5Z8j69OLNKHYQyvupIZN4ok/vwFnrSZRgbP3mMtlwB6XSzpM7XxmT2EC0kGxV9T21cXoSUR2y4KFaBVz+18r+mDSRXiEWAZfAC6PBDslQAORNO5w4fCWkp48QmK7V8mR3YIoLABb9UUSE7aYJmNUibVGKecWOxT7Z7H3MY3+05TgOIbKJei32wORCXP6x+jKRAdQW0/4pkAoaZrqhWuvjvyJodN4BtiPdTKc5yNG5/rc0V6KaFiF3GqPW4Xh4xgd+kJQKk0NsS+GLdZ+RQD3K8jewuJWVoAuE+vT2vkRIR+1ykuUsZHN2cZ6KV3N9SQw6BfNFEwBUmvd+vGipJEYKOftDp5mYEtvZXKeH8LNfa4A97qIbehS61P/MbXbTpBk22xlyB4w09Hp4ZKDe4rD4hSf6NofY4Ua0lW7PlyAIuXjXNr5nI4x957ZlHmg=
    on_success: change
